### ISSUE TITLE
Sample test `test_streaming_automl_action_recognition` failing with "The Model does not exist."

### ISSUE THREAD

**Issue by parthea** [googleapis/python-videointelligence#311]
In the past week samples test `test_streaming_automl_action_recognition` has started failing with "The Model does not exist"

Stack Trace
```
=================================== FAILURES ===================================
___________________ test_streaming_automl_action_recognition ___________________

capsys = <_pytest.capture.CaptureFixture object at 0x7f253f6cfb80>
video_path = '/tmp/pytest-of-kbuilder/pytest-0/video0/file.mp4'

    @pytest.mark.flaky(max_runs=3, min_passes=1)
    def test_streaming_automl_action_recognition(capsys, video_path):
        project_id = os.environ["GOOGLE_CLOUD_PROJECT"]
        model_id = "2509833202491719680"
        beta_snippets.streaming_automl_action_recognition(video_path, project_id, model_id)
        out, _ = capsys.readouterr()
>       assert "segment" in out
E       AssertionError: assert 'segment' in 'com.google.cloud.ai.platform.common.errors.AiPlatformException: code=NOT_FOUND, message=The Model does not exist., cause=null\n'
````

See https://github.com/googleapis/python-videointelligence/pull/309 and build log [here](https://source.cloud.google.com/results/invocations/1aca5325-27e2-409f-bf51-29be4a45bf00/log).

**Comment by galz10** [comment]
Hi @parthea there was an issue with our service account i think this was the cause for a lot of failures now the service account is fixed and everything passes.

**Comment by parthea** [comment]
Hi @galz10 ,
The issue is still occurring. Can you confirm that the service account was fixed?
